package view;

import control.DAO;
import java.awt.Color;
import static java.sql.JDBCType.NULL;
import java.util.Iterator;
import view.AddStudentView;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author hai
 */
public class AdminView extends javax.swing.JFrame {

    /*======================= ATTRIBUTEs ==============================*/
    private String adminID;
    DefaultTableModel modelSinhVien;

    /*======================= CONSTRUCOTORs ==============================*/
    /**
     * Creates new form AdminView
     */
    DAO std = new DAO();

    public AdminView(String adminID) {
        initComponents();
        this.adminID = adminID;
       // std.fillStudentJtable(jTable1, "");
      //  AdminView.displaySinhVien();
        std.fillCourseJtable(jTable_hocphan, "");
        modelSinhVien = (DefaultTableModel) jTable1.getModel();
        jTable1.setRowHeight(40);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.yellow);
        jTable1.setSelectionBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_hovaten = new javax.swing.JLabel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_mssv = new javax.swing.JLabel();
        jLabel_hesinhvien = new javax.swing.JLabel();
        jLabel_machuongtrinh = new javax.swing.JLabel();
        jLabel_malop = new javax.swing.JLabel();
        jLabel_trangthaihoctap = new javax.swing.JLabel();
        jTextField_hovaten = new javax.swing.JTextField();
        jTextField_mssv = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jRadioButtonnc = new javax.swing.JRadioButton();
        jRadioButtontc = new javax.swing.JRadioButton();
        jTextField_manganhhoc = new javax.swing.JTextField();
        jLabel_manghanhhoc = new javax.swing.JLabel();
        jTextField_machuongtrinhhoc = new javax.swing.JTextField();
        jTextField_malop = new javax.swing.JTextField();
        jTextField_trangthaihoctap = new javax.swing.JTextField();
        jLabel_find = new javax.swing.JLabel();
        jTextField_find = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton_add = new javax.swing.JButton();
        jButton_edit = new javax.swing.JButton();
        jButton_remove = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_mahocphan = new javax.swing.JLabel();
        jLabel_tenhocphan = new javax.swing.JLabel();
        jLabel_trongsogiuaki = new javax.swing.JLabel();
        jLabel_trongsocuoiki = new javax.swing.JLabel();
        jLabel_hehocphan = new javax.swing.JLabel();
        jLabel_stthocki = new javax.swing.JLabel();
        jTextField_mahocphan = new javax.swing.JTextField();
        jTextField_tenhocphan = new javax.swing.JTextField();
        jTextField_trongsogiuaky = new javax.swing.JTextField();
        jTextField_trongsocuoiki = new javax.swing.JTextField();
        jTextField_hehocphan = new javax.swing.JTextField();
        jTextField_stthocki = new javax.swing.JTextField();
        jButton_add1 = new javax.swing.JButton();
        jButton_remove1 = new javax.swing.JButton();
        jLabel_find1 = new javax.swing.JLabel();
        jTextField_find1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable_hocphan = new javax.swing.JTable();
        jLabel_thp = new javax.swing.JLabel();
        jLabel_mhp = new javax.swing.JLabel();
        jLabel_tsgk = new javax.swing.JLabel();
        jLabel_tsck = new javax.swing.JLabel();
        jLabel_hhp = new javax.swing.JLabel();
        jLabel_stthk = new javax.swing.JLabel();
        jButton1_editcourse = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel_qlht_mssv = new javax.swing.JLabel();
        jLabel_qlht_hp = new javax.swing.JLabel();
        jLabel_qlht_dgk = new javax.swing.JLabel();
        jLabel_qlht_dck = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel_admin = new javax.swing.JLabel();
        jButtonDangXuat = new javax.swing.JButton();

        jScrollPane1.setViewportView(jTree1);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 102));

        jTabbedPane3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTabbedPane3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("Manage Student");

        jLabel_hovaten.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_hovaten.setText("Ho va ten:");

        jLabel_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_username.setText("username:");

        jLabel_mssv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_mssv.setText("MSSV:");

        jLabel_hesinhvien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_hesinhvien.setText("He Sinh Vien:");

        jLabel_machuongtrinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_machuongtrinh.setText("Ma chuong trinh:");

        jLabel_malop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_malop.setText("Ma lop:");

        jLabel_trangthaihoctap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_trangthaihoctap.setText("Trang thai  ht:");

        jTextField_hovaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_hovatenActionPerformed(evt);
            }
        });

        jTextField_mssv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mssvActionPerformed(evt);
            }
        });

        jRadioButtonnc.setText("NC");
        jRadioButtonnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonncActionPerformed(evt);
            }
        });

        jRadioButtontc.setText("TC");

        jTextField_manganhhoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_manganhhocActionPerformed(evt);
            }
        });

        jLabel_manghanhhoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_manghanhhoc.setText("Ma nganh:");

        jTextField_malop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_malopActionPerformed(evt);
            }
        });

        jTextField_trangthaihoctap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_trangthaihoctapActionPerformed(evt);
            }
        });

        jLabel_find.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_find.setText("Enter value to search");

        jTextField_find.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_findActionPerformed(evt);
            }
        });
        jTextField_find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_findKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_findKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "heSinhVien", "mssv", "hoTen", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "hocki"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        jButton_edit.setText("Edit");
        jButton_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_editActionPerformed(evt);
            }
        });

        jButton_remove.setText("Remove");
        jButton_remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_removeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel_find)
                .addGap(33, 33, 33)
                .addComponent(jTextField_find, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_mssv)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_hovaten)
                            .addComponent(jLabel_username)
                            .addComponent(jLabel_hesinhvien)
                            .addComponent(jLabel_manghanhhoc))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jRadioButtonnc)
                                        .addGap(90, 90, 90)
                                        .addComponent(jRadioButtontc))
                                    .addComponent(jTextField_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_manganhhoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_hovaten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel_trangthaihoctap)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_trangthaihoctap, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel_malop)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_malop, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel_machuongtrinh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_machuongtrinhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton_remove)
                        .addGap(20, 20, 20)
                        .addComponent(jButton_edit)
                        .addGap(56, 56, 56)
                        .addComponent(jButton_add)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_find)
                            .addComponent(jTextField_find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_hovaten)
                            .addComponent(jTextField_hovaten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_username)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_mssv)
                            .addComponent(jTextField_mssv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_hesinhvien)
                            .addComponent(jRadioButtonnc)
                            .addComponent(jRadioButtontc))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_manghanhhoc)
                            .addComponent(jTextField_manganhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_machuongtrinhhoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_machuongtrinh))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_malop)
                            .addComponent(jTextField_malop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_trangthaihoctap)
                            .addComponent(jTextField_trangthaihoctap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_add)
                            .addComponent(jButton_edit)
                            .addComponent(jButton_remove))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                        .addContainerGap())))
        );

       

        jTabbedPane3.addTab("Thêm sửa xóa", jPanel7);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        jTabbedPane1.addTab("Quản lý sinh viên", jPanel1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Quản lý ngành học", jPanel10);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Quản lý chương trình học", jPanel11);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane4.addTab("Quản lý lớp sinh viên", jPanel12);

        jPanel13.setBackground(new java.awt.Color(255, 255, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Add Course");

        jLabel_mahocphan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_mahocphan.setText("Ma Hoc Phan:");

        jLabel_tenhocphan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_tenhocphan.setText("Ten Hoc Phan:");

        jLabel_trongsogiuaki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_trongsogiuaki.setText("Trong so giua ki:");

        jLabel_trongsocuoiki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_trongsocuoiki.setText("Trong So Cuoi Ki:");

        jLabel_hehocphan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_hehocphan.setText("He Hoc Phan:");

        jLabel_stthocki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_stthocki.setText("STT hoc ki:");

        jTextField_mahocphan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTextField_mahocphanInputMethodTextChanged(evt);
            }
        });
        jTextField_mahocphan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_mahocphanActionPerformed(evt);
            }
        });

        jTextField_trongsogiuaky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_trongsogiuakyActionPerformed(evt);
            }
        });

        jTextField_stthocki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_stthockiActionPerformed(evt);
            }
        });

        jButton_add1.setBackground(new java.awt.Color(153, 204, 255));
        jButton_add1.setForeground(new java.awt.Color(153, 204, 255));
        jButton_add1.setText("Add");
        jButton_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_add1ActionPerformed(evt);
            }
        });

        jButton_remove1.setForeground(new java.awt.Color(255, 51, 51));
        jButton_remove1.setText("Remove");
        jButton_remove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_remove1ActionPerformed(evt);
            }
        });

        jLabel_find1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_find1.setText("Enter value to search");

        jTextField_find1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_find1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_find1ActionPerformed(evt);
            }
        });
        jTextField_find1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_find1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_find1KeyReleased(evt);
            }
        });

        jTable_hocphan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "maHocPhan", "tenHocPhan", "trongSoGK", "trongSoCK", "heHocPhan", "sttHK"
            }
        ));
        jTable_hocphan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_hocphanMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable_hocphan);

        jLabel_thp.setText("*");

        jLabel_mhp.setText("*");

        jLabel_tsgk.setText("*");

        jLabel_tsck.setText("*");

        jLabel_hhp.setText("*");

        jLabel_stthk.setText("*");

        jButton1_editcourse.setText("Edit");
        jButton1_editcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_editcourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jButton_remove1)
                        .addGap(52, 52, 52)
                        .addComponent(jButton1_editcourse)
                        .addGap(58, 58, 58)
                        .addComponent(jButton_add1))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                            .addComponent(jLabel_mahocphan)
                                            .addGap(18, 18, 18)
                                            .addComponent(jTextField_mahocphan, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel13Layout.createSequentialGroup()
                                            .addComponent(jLabel_tenhocphan)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField_tenhocphan, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel13Layout.createSequentialGroup()
                                        .addComponent(jLabel_trongsogiuaki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_trongsogiuaky, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel13Layout.createSequentialGroup()
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel_trongsocuoiki)
                                        .addComponent(jLabel_hehocphan))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField_hehocphan, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_trongsocuoiki, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField_stthocki, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel_stthocki))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_tsck)
                            .addComponent(jLabel_hhp)
                            .addComponent(jLabel_tsgk)
                            .addComponent(jLabel_thp)
                            .addComponent(jLabel_mhp)
                            .addComponent(jLabel_stthk))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_find1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_find1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_find1)
                            .addComponent(jTextField_find1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_mahocphan)
                            .addComponent(jTextField_mahocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_mhp))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_tenhocphan)
                            .addComponent(jTextField_tenhocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_thp))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_trongsogiuaki)
                            .addComponent(jTextField_trongsogiuaky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tsgk))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_trongsocuoiki)
                            .addComponent(jTextField_trongsocuoiki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_tsck))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_hehocphan)
                            .addComponent(jTextField_hehocphan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_hhp))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_stthocki)
                            .addComponent(jTextField_stthocki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_stthk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_add1)
                            .addComponent(jButton_remove1)
                            .addComponent(jButton1_editcourse))
                        .addGap(51, 51, 51))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jTabbedPane4.addTab("Quản lý học phần", jPanel13);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        jTabbedPane1.addTab("Quản lý đào tạo", jPanel2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Đăng ký học phần", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Đăng ký lớp", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Tra cứu lớp mở", jPanel6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Xét tốt nghiệp", jPanel9);

        jPanel8.setBackground(new java.awt.Color(255, 255, 102));

        jLabel_qlht_mssv.setText("MSSV:");

        jLabel_qlht_hp.setText("Hoc Phan:");

        jLabel_qlht_dgk.setText("Diem Giua Ky");

        jLabel_qlht_dck.setText("Diem Cuoi Ky:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_qlht_mssv)
                            .addComponent(jLabel_qlht_dgk)
                            .addComponent(jLabel_qlht_dck)
                            .addComponent(jLabel_qlht_hp))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1))))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_qlht_mssv)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_qlht_hp)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_qlht_dgk)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_qlht_dck)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addContainerGap())))
        );

        jTabbedPane2.addTab("Nhập kết quả học tập", jPanel8);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane1.addTab("Quản lý học tập", jPanel3);

        jLabel_admin.setText("Tên admin");

        jButtonDangXuat.setText("Đăng xuât");
        jButtonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_admin)
                .addGap(18, 18, 18)
                .addComponent(jButtonDangXuat)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_admin)
                    .addComponent(jButtonDangXuat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void displaySinhVien() {
       // AdminView.jTable1.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien", "mssv", "hoTen", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "bangTN"}));
        modelSinhVien.setRowCount(0);
        HeThong.getListSinhVien().forEach((s) -> {
            if (s instanceof SinhVienTC) {
                modelSinhVien.addRow(new Object[]{
                    "TC", s.getMssv(),s.getHoTen(),s.getUsername(),s.getMaNganhHoc(),s.getMaChuongTrinhHoc(),s.getMaLopSinhVien(),s.getTrangThai(),s.getBangTotNghiep()
                        
                });
            } else {
                modelSinhVien.addRow(new Object[]{
                    "NC", s.getMssv(),s.getHoTen(),s.getUsername(),s.getMaNganhHoc(),s.getMaChuongTrinhHoc(),s.getMaLopSinhVien(),s.getTrangThai(),s.getBangTotNghiep()
                  
                });

            }
        });
    }
    private void jButtonDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDangXuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        HeThong.initLoginSession();
    }//GEN-LAST:event_jButtonDangXuatActionPerformed

    private void jTabbedPane3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTabbedPane3AncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_jTabbedPane3AncestorAdded

    private void jTextField_hovatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_hovatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_hovatenActionPerformed

    private void jTextField_mssvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mssvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mssvActionPerformed

    private void jRadioButtonncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonncActionPerformed

    private void jTextField_manganhhocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_manganhhocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_manganhhocActionPerformed

    private void jTextField_malopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_malopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_malopActionPerformed

    private void jTextField_trangthaihoctapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_trangthaihoctapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_trangthaihoctapActionPerformed

    private void jTextField_findActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_findActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_findActionPerformed

    private void jTextField_findKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_findKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_findKeyPressed

    private void jTextField_findKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_findKeyReleased
        // TODO add your handling code here:
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien", "mssv", "hoTen", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "bangTN"}));
        std.fillStudentJtable(jTable1, jTextField_find.getText());
    }//GEN-LAST:event_jTextField_findKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        if (model.getValueAt(rowIndex, 0).equals("TC")) {
            jRadioButtontc.setSelected(true);
            jRadioButtonnc.setSelected(false);

        } else {
            jRadioButtonnc.setSelected(true);
            jRadioButtontc.setSelected(false);
        }
        jTextField_mssv.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_username.setText(model.getValueAt(rowIndex, 3).toString());
        jTextField_hovaten.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_manganhhoc.setText(model.getValueAt(rowIndex, 4).toString());
        jTextField_machuongtrinhhoc.setText(model.getValueAt(rowIndex, 5).toString());
        jTextField_malop.setText(model.getValueAt(rowIndex, 6).toString());
        //jTextField_.setText(model.getValueAt(rowIndex,8).toString());
        jTextField_trangthaihoctap.setText(model.getValueAt(rowIndex, 7).toString());
        //   jTextField_bangtotnghiep.setText(model.getValueAt(rowIndex,8).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addActionPerformed
        // //
        this.setVisible(true);
        AddStudentView addstd = new AddStudentView();
        addstd.setVisible(true);
        //manageStudent mngstd = new manageStudent();
        //mngstd.setVisible(true);
        addstd.pack();
        addstd.setLocationRelativeTo(null);
        addstd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.displaySinhVien();
    }//GEN-LAST:event_jButton_addActionPerformed

    private void jButton_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_editActionPerformed
        // TODO add your handling code here:
        String hoTen = jTextField_hovaten.getText();
        String username = jTextField_username.getText();
        String mssv = jTextField_mssv.getText();
        String maNganhHoc = jTextField_manganhhoc.getText();
        String maChuongTrinhHoc = jTextField_machuongtrinhhoc.getText();
        String maLopSinhVien = jTextField_malop.getText();
        String trangThaiHocTap = jTextField_trangthaihoctap.getText();
        //String bangTotNghiep = jTextField_bangtotnghiep.getText();
        String heSinhVien = "TC";
        if (jRadioButtonnc.isSelected()) {
            heSinhVien = "NC";
        }

        //SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        // String bdate = dateFormat.format(dateChooserCombo.getSelectedDate());
        if (verifText()) {
            DAO std = new DAO();
            std.insertDeleteUpdateStudent('u', null, heSinhVien, mssv, hoTen, username, username, maNganhHoc, maChuongTrinhHoc, maLopSinhVien, trangThaiHocTap, null);
            //update object
            for (int i = 0; i < HeThong.getListSinhVien().size() - 1; i++) {
                if (HeThong.getListSinhVien().get(i).getMssv().equals("mssv")) {
                    HeThong.getListSinhVien().get(i).setUsername(username);
                    HeThong.getListSinhVien().get(i).setPassword(username);
                    HeThong.getListSinhVien().get(i).setMssv(mssv);
                    HeThong.getListSinhVien().get(i).setTrangThai(trangThaiHocTap);
                    HeThong.getListSinhVien().get(i).setMaNganhHoc(maNganhHoc);
                    HeThong.getListSinhVien().get(i).setMaLopSinhVien(maLopSinhVien);
                    HeThong.getListSinhVien().get(i).setMaChuongTrinhHoc(maChuongTrinhHoc);
                    HeThong.getListSinhVien().get(i).setHoTen(hoTen);
                    // HeThong.getListSinhVien().get(i).setBangTotNghiep(maNganhHoc);
                    HeThong.findLopSinhVien(maLopSinhVien).getSinhVien().add(HeThong.getListSinhVien().get(i));
                }
            }

            AdminView.jTable1.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien", "mssv", "hoTen", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "bangTN"}));
            std.fillStudentJtable(AdminView.jTable1, "");
        }
    }//GEN-LAST:event_jButton_editActionPerformed
    public boolean verifText() {
        if (jTextField_hovaten.getText().equals("") || jTextField_username.getText().equals("") || jTextField_mssv.getText().equals("")
                || jTextField_manganhhoc.getText().equals("") || jTextField_machuongtrinhhoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "One or more empty field");
            return false;
        } else {
            return true;
        }

    }
    private void jButton_removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_removeActionPerformed
//        // TODO add your handling code here:
        //this.dispose();
        if (jTextField_hovaten.getText().equals("") || jTextField_username.getText().equals("") || jTextField_mssv.getText().equals("")
                || jTextField_manganhhoc.getText().equals("") || jTextField_machuongtrinhhoc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No selected student");
        } else {
            String mssv = jTextField_mssv.getText();
            std.insertDeleteUpdateStudent('d', null, null, mssv, null, null, null, null, null, null, null, null);
            //AdminView.jTable1.setModel(new DefaultTableModel(null, new Object[]{"heSinhVien", "mssv", "hoTen", "username", "maNganh", "maChuongTrinh", "maLop", "trangThai", "bangTN"}));
            //std.fillStudentJtable(AdminView.jTable1, "");
            //HeThong.getListSinhVien().iterator()
           // 
            //HeThong.findSinhVien(mssv).getBangDiem().clear();
            
            //HeThong.findSinhVien(mssv).getHocKySinhVien().clear();
            HeThong.findLopSinhVien(jTextField_malop.getText()).getSinhVien().remove(HeThong.findSinhVien(mssv));
            HeThong.getListSinhVien().remove(HeThong.findSinhVien(mssv));
            
            this.displaySinhVien();
            System.out.println("yes");
        }
    }//GEN-LAST:event_jButton_removeActionPerformed

    private void jTextField_trongsogiuakyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_trongsogiuakyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_trongsogiuakyActionPerformed

    private void jButton_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_add1ActionPerformed
        // TODO add your handling code here:
        DAO dao = new DAO();

        jLabel_mhp.setVisible(false);
        jLabel_thp.setVisible(false);
        jLabel_tsgk.setVisible(false);
        jLabel_tsck.setVisible(false);
        jLabel_hhp.setVisible(false);
        jLabel_stthk.setVisible(false);
        Boolean error = false;
        Float trongSoGiuaKy = 0.0f, trongSoCuoiKy = 0.0f;
        String maHocPhan = jTextField_mahocphan.getText();
        if (maHocPhan.equals("")) {
            jLabel_mhp.setVisible(true);
            error = true;
        }
        String tenHocPhan = jTextField_tenhocphan.getText();
        if (tenHocPhan.equals("")) {
            jLabel_thp.setVisible(true);
            error = true;
        }
        String trongSoGiua = jTextField_trongsogiuaky.getText();
        if (trongSoGiua.equals("")) {
            jLabel_tsgk.setVisible(true);
            error = true;
        } else {
            trongSoGiuaKy = Float.parseFloat(trongSoGiua);
        }
        String trongSoCuoi = jTextField_trongsocuoiki.getText();
        if (trongSoCuoi.equals("")) {
            jLabel_tsck.setVisible(true);
            error = true;
        } else {
            trongSoCuoiKy = Float.parseFloat(trongSoCuoi);
        }
        // Float trongSoCuoiKy = Float.parseFloat(trongSoCuoi);
        String heHocPhan = jTextField_hehocphan.getText();
        if (heHocPhan.equals("")) {
            jLabel_hhp.setVisible(true);
            error = true;
        }

        String sttHocKy = jTextField_stthocki.getText();

        if (dao.isCourseExist(maHocPhan)) {
            JOptionPane.showMessageDialog(null, "Course is exist");
        }

        if (error == false && !dao.isCourseExist(maHocPhan)) {
            dao.insertDeleteUpdateCourse('i', maHocPhan, tenHocPhan, trongSoGiuaKy, trongSoCuoiKy, heHocPhan, sttHocKy);
            AdminView.jTable_hocphan.setModel(new DefaultTableModel(null, new Object[]{"maHocPhan", "tenHocPhan", "trongSoGiuaKy", "trongSoCuoiKy", "heHocPhan", "sttHocKy"}));
            dao.fillCourseJtable(jTable_hocphan, "");
        }

        // return;

    }//GEN-LAST:event_jButton_add1ActionPerformed

    private void jButton_remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_remove1ActionPerformed
        // TODO add your handling code here:
        DAO course = new DAO();

        if (jTextField_mahocphan.getText().equals("") || jTextField_tenhocphan.getText().equals("") || jTextField_trongsogiuaky.getText().equals("")
                || jTextField_trongsocuoiki.getText().equals("") || jTextField_hehocphan.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No selected course");
        } else {
            String maHocPhan = jTextField_mahocphan.getText();
            course.insertDeleteUpdateCourse('d', maHocPhan, null, null, null, null, null);
            AdminView.jTable_hocphan.setModel(new DefaultTableModel(null, new Object[]{"maHocPhan", "tenHocPhan", "trongSoGiuaKy", "trongSoCuoiKy", "heHocPhan", "sttHocKy"}));
            course.fillCourseJtable(AdminView.jTable_hocphan, "");
        }

    }//GEN-LAST:event_jButton_remove1ActionPerformed

    private void jTextField_find1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_find1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_find1ActionPerformed

    private void jTextField_find1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_find1KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_find1KeyPressed

    private void jTextField_find1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_find1KeyReleased
        // TODO add your handling code here:
        DAO course = new DAO();
        jTable_hocphan.setModel(new DefaultTableModel(null, new Object[]{"maHocPhan", "tenHocPhan", "trongSoGiuaKy", "trongSoCuoiKy", "heHocPhan", "sttHocKy"}));
        course.fillCourseJtable(jTable_hocphan, jTextField_find1.getText());
    }//GEN-LAST:event_jTextField_find1KeyReleased

    private void jTable_hocphanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_hocphanMouseClicked
        // TODO add your handling code here:
        int rowIndex = jTable_hocphan.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable_hocphan.getModel();

        jTextField_mahocphan.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField_tenhocphan.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_trongsogiuaky.setText(model.getValueAt(rowIndex, 2).toString());
        jTextField_trongsocuoiki.setText(model.getValueAt(rowIndex, 3).toString());
        jTextField_hehocphan.setText(model.getValueAt(rowIndex, 4).toString());

        if (model.getValueAt(rowIndex, 5) != null) {
            jTextField_stthocki.setText(model.getValueAt(rowIndex, 5).toString());
        } else {
            jTextField_stthocki.setText("NULL");
        }
    }//GEN-LAST:event_jTable_hocphanMouseClicked

    private void jTextField_mahocphanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_mahocphanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_mahocphanActionPerformed

    private void jTextField_stthockiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_stthockiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_stthockiActionPerformed

    private void jButton1_editcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_editcourseActionPerformed
        // TODO add your handling code here:
        Float trongSoGiuaKy = 0.0f, trongSoCuoiKy = 0.0f;
        String mahocphan = jTextField_mahocphan.getText();
        String tenhocphan = jTextField_tenhocphan.getText();
        String trongsogiuaky = jTextField_trongsogiuaky.getText();
        trongSoGiuaKy = Float.parseFloat(trongsogiuaky);
        String trongsocuoiky = jTextField_trongsocuoiki.getText();
        trongSoCuoiKy = Float.parseFloat(trongsocuoiky);
        String hehocphan = jTextField_hehocphan.getText();
        String stthocky = jTextField_stthocki.getText();

        //if(verifText()){
        DAO std = new DAO();
        std.insertDeleteUpdateCourse('u', mahocphan, tenhocphan, trongSoGiuaKy, trongSoCuoiKy, hehocphan, stthocky);
        AdminView.jTable_hocphan.setModel(new DefaultTableModel(null, new Object[]{"maHocPhan", "tenHocPhan", "trongSoGiuaKy", "trongSoCuoiKy", "heHocPhan", "sttHocKy"}));
        std.fillCourseJtable(AdminView.jTable_hocphan, "");
        //}

    }//GEN-LAST:event_jButton1_editcourseActionPerformed

    private void jTextField_mahocphanInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTextField_mahocphanInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_mahocphanInputMethodTextChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
//	public static void main(String args[]) {
//		/* Set the Nimbus look and feel */
//		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//		 */
//		try {
//			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//				if ("Nimbus".equals(info.getName())) {
//					javax.swing.UIManager.setLookAndFeel(info.getClassName());
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger(AdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//		}
//		//</editor-fold>
//		//</editor-fold>
//
//		/* Create and display the form */
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new AdminView().setVisible(true);
//			}
//		});
//	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton1_editcourse;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDangXuat;
    private javax.swing.JButton jButton_add;
    private javax.swing.JButton jButton_add1;
    private javax.swing.JButton jButton_edit;
    private javax.swing.JButton jButton_remove;
    private javax.swing.JButton jButton_remove1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel_admin;
    private javax.swing.JLabel jLabel_find;
    private javax.swing.JLabel jLabel_find1;
    private javax.swing.JLabel jLabel_hehocphan;
    private javax.swing.JLabel jLabel_hesinhvien;
    private javax.swing.JLabel jLabel_hhp;
    private javax.swing.JLabel jLabel_hovaten;
    private javax.swing.JLabel jLabel_machuongtrinh;
    private javax.swing.JLabel jLabel_mahocphan;
    private javax.swing.JLabel jLabel_malop;
    private javax.swing.JLabel jLabel_manghanhhoc;
    private javax.swing.JLabel jLabel_mhp;
    private javax.swing.JLabel jLabel_mssv;
    private javax.swing.JLabel jLabel_qlht_dck;
    private javax.swing.JLabel jLabel_qlht_dgk;
    private javax.swing.JLabel jLabel_qlht_hp;
    private javax.swing.JLabel jLabel_qlht_mssv;
    private javax.swing.JLabel jLabel_stthk;
    private javax.swing.JLabel jLabel_stthocki;
    private javax.swing.JLabel jLabel_tenhocphan;
    private javax.swing.JLabel jLabel_thp;
    private javax.swing.JLabel jLabel_trangthaihoctap;
    private javax.swing.JLabel jLabel_trongsocuoiki;
    private javax.swing.JLabel jLabel_trongsogiuaki;
    private javax.swing.JLabel jLabel_tsck;
    private javax.swing.JLabel jLabel_tsgk;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButtonnc;
    private javax.swing.JRadioButton jRadioButtontc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    public static javax.swing.JTable jTable_hocphan;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField_find;
    private javax.swing.JTextField jTextField_find1;
    private javax.swing.JTextField jTextField_hehocphan;
    private javax.swing.JTextField jTextField_hovaten;
    private javax.swing.JTextField jTextField_machuongtrinhhoc;
    private javax.swing.JTextField jTextField_mahocphan;
    private javax.swing.JTextField jTextField_malop;
    private javax.swing.JTextField jTextField_manganhhoc;
    private javax.swing.JTextField jTextField_mssv;
    private javax.swing.JTextField jTextField_stthocki;
    private javax.swing.JTextField jTextField_tenhocphan;
    private javax.swing.JTextField jTextField_trangthaihoctap;
    private javax.swing.JTextField jTextField_trongsocuoiki;
    private javax.swing.JTextField jTextField_trongsogiuaky;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
